# =============================================================================
# COMPOSITE ACTION: Project Setup
# =============================================================================
# Reusable setup for Node.js, npm dependencies, and optional Playwright.
# Eliminates 6x duplication across CI jobs.
#
# Usage:
#   - uses: ./.github/actions/setup
#   - uses: ./.github/actions/setup
#     with:
#       install-playwright: 'true'
# =============================================================================

name: 'Project Setup'
description: 'Node.js 22, npm cache, dependency install, optional Playwright browsers'

inputs:
  install-playwright:
    description: 'Install Playwright browsers (chromium)'
    default: 'false'
  node-version:
    description: 'Node.js version'
    default: '22'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
      shell: bash

    # Playwright browser caching (~500MB savings per cache hit)
    # Version is auto-detected from installed package to prevent cache staleness
    - name: Detect Playwright version
      if: inputs.install-playwright == 'true'
      id: pw-version
      run: echo "version=$(node -p 'require("@playwright/test/package.json").version')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Playwright browsers
      if: inputs.install-playwright == 'true'
      uses: actions/cache@v5
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ steps.pw-version.outputs.version }}-${{ runner.os }}

    - name: Install Playwright browsers (full)
      if: inputs.install-playwright == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium
      shell: bash

    - name: Install Playwright OS deps only (cached)
      if: inputs.install-playwright == 'true' && steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps chromium
      shell: bash
