name: Bug report
description: Report a reproducible bug or regression.
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear summary of the problem.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Numbered steps that reproduce the issue reliably.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happens.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Runtime, OS, browser, branch, commit, and relevant config.
      placeholder: |
        - OS:
        - Browser:
        - Node:
        - Branch:
        - Commit:
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs
      description: Attach screenshots, stack traces, or relevant logs.
    validations:
      required: false
