name: Feature request
description: Propose a new capability or enhancement.
title: '[Feature]: '
labels:
  - enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short summary of the feature request.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Problem or opportunity this feature addresses.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Preferred implementation approach.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches considered and why they were not chosen.
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Testable conditions for completion.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
