name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: a8d9c67f586acdd15eebcc65ca3aa5bb
          command: pages deploy docs --project-name=resume --branch=main --commit-dirty=true
