name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: a8d9c67f586acdd15eebcc65ca3aa5bb
          projectName: resume-jclee-me
          directory: docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
