name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Tag and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          default_bump: patch

      - name: Diagnostic
        run: echo "Tag step succeeded - ${{ steps.tag_version.outputs.new_tag }}"
